### ISSUE TITLE
How do I get Impostor API 1.6.0?

### ISSUE THREAD

**Issue by Krilgone** [Trinculo54/Trinculo54s_Gamemodes#1]
In Gamemodes.csproj, I see you have the following:
`<PackageReference Include="Impostor.Api" Version="1.6.0-ci.12" />`

How can I also get that version? I can only see up to version 1.4.0 [here](https://www.nuget.org/packages/Impostor.Api/)

Thank you!

**Comment by Trinculo54** [comment]
Hey Krilgone!, This is build with my custom build of Impostor.Api and Server that allows sending data to players.

You Get it [Here](https://ci.appveyor.com/project/Trinculo54/impostor/build/artifacts)

**Comment by Krilgone** [comment]
Ah, Thank you!

Is the source code for the custom build available online? I'd love to be able to use `SendSettingsToPlayerAsync` !

(Sorry if this is a bad place to ask questions, I didn't know where else to ask :) )

**Comment by Trinculo54** [comment]
Yea, the source is available through github [https://github.com/Trinculo54/Impostor](https://github.com/Trinculo54/Impostor), happy coding!
